database:
  app_db_name: dbos_exp
  hostname: localhost
  migrate:
  - alembic upgrade head
  password: dbos
  port: 5432
  username: postgres
language: python
name: dbos_experiments
runtimeConfig:
  start:
  - python resume.py
telemetry:
  OTLPExporter:
    logsEndpoint: http://localhost:4317/v1/logs
    tracesEndpoint: http://localhost:4317/v1/traces
  logs:
    addContextMetadata: true
    logLevel: INFO
