# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: dbos_experiments
language: python
runtimeConfig:
  start:
    - "fastapi dev main.py"
database:
  hostname: ${PGHOST}
  port: ${PGPORT}
  username: ${PGUSER}
  password: ${PGPASSWORD}
  app_db_name: ${PGDATABASE}
  sys_db_name: dbos_history
  migrate:
    - alembic upgrade head
telemetry:
  OTLPExporter:
    logsEndpoint: http://localhost:4317/v1/logs
    tracesEndpoint: http://localhost:4317/v1/traces
  logs:
    addContextMetadata: true
    logLevel: DEBUG
